name: samify
description: A modern music streaming application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # firebase_core: ^2.15.1
  # firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  just_audio: ^0.9.34
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.1
  path_provider: ^2.1.1
  permission_handler: ^10.4.3
  # google_sign_in: ^6.1.5
  # flutter_facebook_auth: ^6.0.1
  dio: ^4.0.0
  http: ^0.13.3
  # flutter_web_auth: ^0.3.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
 

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700